### ISSUE TITLE
Docker Test run unable to find phantom

### ISSUE THREAD

**Issue by fionnbharra** [wearefriday/spectre#85]
When I run `docker-compose run --rm app bin/demo_test_run http://app:3000` I get the following:

```
Created Spectre run
Traceback (most recent call last):
	12: from bin/demo_test_run:156:in `<main>'
	11: from bin/demo_test_run:67:in `demo_run_with_screenshots'
	10: from /usr/local/bundle/gems/capybara-3.18.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
	 9: from /usr/local/bundle/gems/capybara-3.18.0/lib/capybara/session.rb:277:in `visit'
	 8: from /usr/local/bundle/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:100:in `visit'
	 7: from /usr/local/bundle/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:27:in `browser'
	 6: from /usr/local/bundle/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:47:in `client'
	 5: from /usr/local/bundle/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:16:in `start'
	 4: from /usr/local/bundle/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:16:in `new'
	 3: from /usr/local/bundle/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:53:in `initialize'
	 2: from /usr/local/bundle/gems/cliver-0.3.2/lib/cliver.rb:24:in `detect!'
	 1: from /usr/local/bundle/gems/cliver-0.3.2/lib/cliver/dependency.rb:117:in `detect!'
/usr/local/bundle/gems/cliver-0.3.2/lib/cliver/dependency.rb:151:in `raise_version_mismatch!': Could not find an executable 'phantomjs' that matched the requirements '>= 1.8.1', '< 3.0'. Found versions were {"/usr/local/bin/phantomjs"=>"140385087622784"}. (Cliver::Dependency::VersionMismatch)
```

A project and run are created but no screenshot is sent to the app.

**Comment by jehcriss42** [comment]
To fix add bellow env in docker-compose file.
 OPENSSL_CONF=/etc/ssl/

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
