### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by mac-dev** [wearefriday/spectre#89]
Any ideas?

```
λ docker-compose up
Starting spectre_db_1 ... done
Starting spectre_app_1 ... done
Attaching to spectre_db_1, spectre_app_1
db_1   |
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1   |
db_1   | LOG:  database system was shut down at 2020-07-28 15:09:59 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  autovacuum launcher started
db_1   | LOG:  database system is ready to accept connections
app_1  | /usr/local/bundle/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_1' is reserved for numbered parameter; consider another name
app_1  | /usr/local/bundle/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_2' is reserved for numbered parameter; consider another name
app_1  | /usr/local/bundle/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_3' is reserved for numbered parameter; consider another name
app_1  | /usr/local/bundle/gems/tzinfo-1.2.5/lib/tzinfo/ruby_core_support.rb:142: warning: Using the last argument as keyword parameters is deprecated
app_1  | /usr/local/bundle/gems/tzinfo-1.2.5/lib/tzinfo/ruby_core_support.rb:142: warning: Using the last argument as keyword parameters is deprecated
app_1  | /usr/local/bundle/gems/activerecord-5.0.7.2/lib/active_record/type.rb:22: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
app_1  | /usr/local/bundle/gems/activerecord-5.0.7.2/lib/active_record/type/adapter_specific_registry.rb:7: warning: The called method `add_modifier' is defined here
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:35: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
app_1  | /usr/local/bundle/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/static.rb:113: warning: The called method `initialize' is defined here
app_1  | rake aborted!
app_1  | Errno::EEXIST: File exists @ dir_s_mkdir - /app/tmp/cache/assets/sprockets/v3.0/lf
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cache/file_store.rb:84:in `set'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cache.rb:212:in `set'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cache.rb:136:in `set'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:246:in `store_asset'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:185:in `load_from_unloaded'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
app_1  | /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
app_1  | /usr/local/bundle/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
app_1  | /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
app_1  | Tasks: TOP => assets:precompile
app_1  | (See full trace by running task with --trace)
spectre_app_1 exited with code 1

```

**Comment by Sarvesh-Gupta** [comment]
I'm also facing the same issue on Docker for Windows. On Linux (Ubuntu) setup works as expected.

**Comment by mac-dev** [comment]
Up and running under SLES so it seems to be only a topic on Docker for Windows

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
